name: samsung
channels:
    - defaults
dependencies:
    - python==3.7.13
    - pip==21.2.4 
    - h5py==2.10.0
    - Keras==2.3.1
    - Keras-Applications==1.0.8
    - Keras-Preprocessing==1.1.0
    - matplotlib==3.1.1
    - numpy==1.17.3
    - pandas==0.24.0
    - Pillow==6.2.0
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - pip:
        - opencv-python==4.1.1.26
        - Flask
        - imutils